
language: elixir

elixir:
  - 1.6.0
  - 1.6.1
otp_release:
  - 19.3
  - 20.2

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

scripts:
  - if [[ $(elixir --version) = *"1.6"* ]]; then mix format --check-formatted; fi
  - mix test
