
language: elixir

elixir:
  - 1.6.0
  - 1.6.1
  - 1.6.6
otp_release:
  - 20.2
  - 20.3
  - 21.0

matrix:
  exclude:
  - elixir: 1.6.0
    otp_release: 21.0
  - elixir: 1.6.1
    otp_release: 21.0

dist: trusty

addons:
  postgresql: '9.6'

before_script:
  - psql -c 'create database alumni_book_test;' -U postgres

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - MIX_ENV=prod mix release.init
  - MIX_ENV=prod mix release --env=prod

scripts:
  - if [[ $(elixir --version) = *"1.6.6"* ]]; then mix format --check-formatted; fi
  - MIX_ENV=test mix test
  - openssl aes-256-cbc -K $encrypted_5d8ce8fda14a_key -iv $encrypted_5d8ce8fda14a_iv -in private_ssh_key.enc -out private_ssh_key -d
  - ssh-add private_ssh_key > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan alumni.book.avval.fr
  - echo "`ssh-keyscan alumni.book.avval.fr`" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - scp -r $TRAVIS_BUILD_DIR/_build/prod/rel/alumni_book ${R_PI_PASSWORD}@alumni.book.avval.fr:/tmp/
